diogolsq/VirtualRunners

app/controllers/users_controller.rb, app/views/users/index.html.erb, config/routes.rb
creating the index page that i forgot.
=> creating the index page to show all the users

app/controllers/races_controller.rb, app/controllers/tracks_controller.rb, app/views/races/show.html.erb, config/routes.rb, test/controllers/races_controller_test.rb
done all the logic of the races
=> created all the races Crud

app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb, db/seeds.rb
Fixing the seed and beautify the Home Page and the Navbar
=> Making homepage pretty

app/controllers/races_controller.rb, app/views/tracks/show.html.erb
creating a ajax logic and anchor so load quicker our button to join the track or signed out
=> Ajaxing the button in the join track.

app/assets/stylesheets/components/_forms.scss, app/views/tracks/new.html.erb
centralize the form, fixed some of the fields, put hints when was necessary
=> fixed the form of creating the track.

Gemfile, Gemfile.lock, app/assets/stylesheets/components/_forms.scss, app/controllers/pages_controller.rb, app/controllers/races_controller.rb, app/models/track.rb, app/views/pages/home.html.erb, app/views/tracks/show.html.erb
Search bar in the bottom working, have to put inside the menu though.
=> Search and few fixes

app/assets/stylesheets/components/_menu.scss
Made the menu css name, that I put footer
=> changing name from footer to menu bar

app/assets/stylesheets/components/_menu.scss, app/views/shared/_menu.html.erb
change the hover color to blue and center the links in the page
=> link hover color and links in menu

app/assets/stylesheets/components/_style4all.scss, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_show.scss, app/assets/stylesheets/pages/_showUser.scss, app/views/layouts/application.html.erb, app/views/users/show.html.erb, db/seeds.rb
still have to prettify the user profile, fixed the menu in everypage was eating the border.
=> Small fix in the seed and organized the user profile.

app/assets/stylesheets/pages/_showUser.scss, app/controllers/users_controller.rb, app/views/users/show.html.erb
created the logic and display of scheduled races and past races in th…e user show page
=> Fixing the display of the user page.

app/assets/stylesheets/components/_card.scss
adding some style to the cards
=> fixing the position and style of the cards

app/assets/stylesheets/components/_map.scss, app/javascript/plugins/init_mapbox.js, app/views/tracks/show.html.erb
took out the zoom of the map and took out all the uselles information in the map display.
=> Mobileadaptionview

app/controllers/tracks_controller.rb, app/views/shared/_menu.html.erb, config/routes.rb, db/seeds.rb
fixed seed no distance
fixed home page 
fixed button join race
=> fixed errors when merging (mapbox and loading home page)

app/controllers/tracks_controller.rb
=> Minorbugwithstrava

app/assets/stylesheets/pages/_showUser.scss, app/controllers/races_controller.rb, app/javascript/packs/application.js, app/javascript/plugins/init_sweetalert.js, app/views/layouts/application.html.erb, app/views/tracks/show.html.erb, app/views/users/show.html.erb, package.json, yarn.lock
Added sweet alert and aos animation to project.
=> Javascriptingthehelloutofit

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_forms.scss, app/assets/stylesheets/components/_menu.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/components/_style4all.scss, app/assets/stylesheets/pages/_showUser.scss, app/views/pages/home.html.erb, app/views/shared/_menu.html.erb, app/views/shared/_navbar.html.erb, app/views/users/show.html.erb
profile page still have to work with.
=> Menu and navbar is done.

app/views/tracks/show.html.erb
fixed typos and div for containers
=> Trackpagetypeanddiv

app/assets/stylesheets/components/_menu.scss, app/views/shared/_menu.html.erb
=> made the logic to button stay pressed to know which page you are

app/assets/stylesheets/pages/_showUser.scss, app/views/users/show.html.erb
=> Profilepagestyle

app/assets/stylesheets/components/_forms.scss, app/views/devise/registrations/edit.html.erb
=> add style to edit user page

app/views/shared/_navbar.html.erb
=> link to tracks

app/assets/stylesheets/components/_forms.scss, app/controllers/tracks_controller.rb, app/views/tracks/index.html.erb, db/seeds.rb
=> Running interface

public/404.html, public/500.html
=> Customize404pages

app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/_showUser.scss
removed the bullet point from Login 
increased the font of hovercard to 16px (pages > _showUser)
=> remove bullet and increase the font

app/assets/stylesheets/components/_alert.scss
change the position of alert to up, when the user login
=> change the position of the alert login

app/views/users/show.html.erb
quick fix when you were trying to see other runner profile, it was br…eaking in two spots of the code
=> fix bugs in profile page.

app/assets/stylesheets/pages/_showUser.scss
Change the padding in profile picture
=> Profile picture

app/assets/stylesheets/pages/_showUser.scss
fixing the problem with the styling of p,h1... that was editing all the pages
=> Style solved of homepage and profile page

app/views/tracks/index.html.erb
took out turbolink in the index that was messing with the JS zoom in …the map, smooth experience now
=> made a smooth experience to zoom the track.

app/assets/stylesheets/components/_navbar.scss
removed the bullet point from login
=> remove the bullet point from login

app/javascript/plugins/init_mapbox.js
=> solving js breaking in the track page

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/config/_fonts.scss
fixed the font breaking in the config variables.
=> Styledecisions

app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_showTrack.scss, app/views/tracks/show.html.erb, db/seeds.rb
finished track show version 2 
did some seeding so be mindfull 
rails db:seed
=> Track show

app/assets/stylesheets/components/_card.scss, app/models/track.rb, app/views/tracks/index.html.erb, db/seeds.rb
=> Changing cards

app/assets/stylesheets/components/_forms.scss
fix the position of strava login
=> centralized the strava login alert

app/assets/stylesheets/pages/_showUser.scss
=> change the size of profile picture

app/assets/stylesheets/pages/_showTrack.scss, app/views/tracks/show.html.erb
move de description of the race and put inside the Description Paragraph, so we had more space to show the countdown
fix the size of the letter in Join Button
=> move the description and fix the font-size of the join button

app/assets/stylesheets/pages/_showTrack.scss
fixed the margin on track-details to increase the space a bit
track-details {
border: solid;
border-color: #f6f6f6;
background-color: #f6f6f6;
border-radius: 20px;
padding: 30px 0px;
margin-left: 10px; - it was 30px;
margin-right: 10px; - it was 30px;
}
=> fix the margin on track-details

app/assets/stylesheets/pages/_showUser.scss
=> fix the font on user name and user description

app/assets/stylesheets/components/_forms.scss, app/views/shared/_navbar.html.erb
Fix the word Track's to TRACKS and beautify the Strava Login Button
=> fix the tracks word and beautify Strava Login Button

app/assets/stylesheets/components/_navbar.scss
fix the Login Button with the decoration
=> removed the text decoration in Login Button

app/assets/stylesheets/components/_navbar.scss
=> fixing login again

app/views/tracks/show.html.erb
there were 2 buttons - the one from bellow was not working correctly, so it was removed
=> Remove the button Join from bellow - it was without JS animation

app/assets/stylesheets/pages/_showTrack.scss, app/views/tracks/show.html.erb
=> fixed double info plus added border radius to card after map

app/controllers/tracks_controller.rb
=> fixed strava api logic

app/controllers/tracks_controller.rb
trying to solve production problem.
=> hotfixtrackscontroller

app/views/tracks/show.html.erb
passed the start index to out of the loop, that way the incremation will work, that was a small bug
=> Place number on the table fixed.

app/views/devise/shared/_links.html.erb
button Login with Strava - change to primary
=> button Strava Login - btn-primary

app/assets/stylesheets/pages/_showTrack.scss, app/views/tracks/show.html.erb
=> fixed instruction
